>P1;UKNP
sequence:UKNP:1    :A:351  :A::::
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*
>P1;2IVN
structure:2IVN:2   :A:308 :A::PYROCOCCUS ABYSSI:1.65:
-----------------------------------LALGIEGTAHTLGIGIVSEDKVLANVFDTLTTEKG-GIHPKEAAEHHARLMKPLLRKALSEAGVSLDDIDVIAFSQGPGLGPALRVVATAARALAVKYRKPIVGVNHCIAHVEITKMFGV-KDPVGLYVSGGNTQVLALEGGRYRVFGETLDIGIGNAIDVFARELGLGFP--GGPKVEKLAEKGEKYIELPYAVKGMDLSFSGLLTEAIR----KYRSGKYRVEDLAYSFQETAFAALVEVTERAVAHTEKDEVVLVGGVAANNRLREMLRIMTEDRGIKFFVPPYDLCRDNGAMIAYTGLRMYKAGISFRLEE*
>P1;2IVP
structure:2IVP:2   :A:308 :A::PYROCOCCUS ABYSSI:2.5:
-----------------------------------LALGIEGTAHTLGIGIVSEDKVLANVFDTLTTEKG-GIHPKEAAEHHARLMKPLLRKALSEAGVSLDDIDVIAFSQGPGLGPALRVVATAARALAVKYRKPIVGVNHCIAHVEITKMFGV-KDPVGLYVSGGNTQVLALEGGRYRVFGETLDIGIGNAIDVFARELGLGFP--GGPKVEKLAEKGEKYIELPYAVKGMDLSFSGLLTEAIR----KYRSGKYRVEDLAYSFQETAFAALVEVTERAVAHTEKDEVVLVGGVAANNRLREMLRIMTEDRGIKFFVPPYDLCRDNGAMIAYTGLRMYKAGISFRLEE*
>P1;2VWB
structure:2VWB:2   :A:300 :A::METHANOCALDOCOCCUS JANNASCHII:3.05:
-----------------------------------------ICLGLEGTAEKTGVGIVTSDGEVLFNKTIM------------EAADHHAETFPKLIKEAFEVV--DKNEIDLIAFSQGPGLGPSLRVTATVARTLSLTLKKPIIGVNHCIAHIEIGKLTTEAEDPLTLYVSGGNTQVIAYVSKKYRVFGETLDIAVGNCLDQFARYVNLPH--PGGPYIEELARKGKKLVDLPYTVKGMDIAFSGLLTAAMRAYDA-----GERLEDICYSLQEYAFSMLTEITERALAHTNKGEVMLVGGVAANNRLREMLKAMCEGQNVDFYVPPKEFCGDNGAMIAWLGLLMHKNG*
>P1;3EN9
structure:3EN9:5   :A:305 :A::Methanocaldococcus jannaschii:2.67:
---------------------------------------PMICLGLEGTAEKTGVGIVTSDGEVLFNKTIM-YKPPKQGINPREAADHHAETFPKLIKEAFEVV--DKNEIDLIAFSQGPGLGPSLRVTATVARTLSLTLKKPIIGVNHCIAHIEIGKLTTEAEDPLTLYVSGGNTQVIAYVSKKYRVFGETLDIAVGNCLDQFARYVNLPH--PGGPYIEELARKGKKLVDLPYTVKGMDIAFSGLLTAAMRAYDA-----GERLEDICYSLQEYAFSMLTEITERALAHTNKGEVMLVGGVAANNRLREMLKAMCEGQNVDFYVPPKEFCGDNGAMIAWLGLLMHKNG*
>P1;3ENO
structure:3ENO:3   :A:311 :A::Thermoplasma acidophilum:3.0201:
---------------------------------MDPMIVLGLEGTAHTISCGIIDESRILAMES-SMYRPKTGGIRPLDAAVHHSEVIDTVISRALEKAKISIHDIDLIGFSMGPGLAPSLRVTATAARTISVLTGKPIIGVNHPLGHIEIGRRVTGAIDPVMLYVSGGNTQVIAHVNGRYRVLGETLDIGIGNMIDKFAREAGIPFP--GGPEIEKLAMKGTKLLDLPYSVKGMDTAFSGILTAALQ----YL-KTGQAIEDISYSIQETAFAMLVEVLERALYVSGKDEILMAGGVALNRRLRDMVTNMAREAGIRSYLTDREYCMDNGIMIAQAALLMYKSGVRMSV*
>P1;3ENO
structure:3ENO:3   :B:311 :B::Thermoplasma acidophilum:3.0201:
---------------------------------MDPMIVLGLEGTAHTISCGIIDESRILAMES-SMYRPKTGGIRPLDAAVHHSEVIDTVISRALEKAKISIHDIDLIGFSMGPGLAPSLRVTATAARTISVLTGKPIIGVNHPLGHIEIGRRVTGAIDPVMLYVSGGNTQVIAHVNGRYRVLGETLDIGIGNMIDKFAREAGIPFP--GGPEIEKLAMKGTKLLDLPYSVKGMDTAFSGILTAALQ----YL-KTGQAIEDISYSIQETAFAMLVEVLERALYVSGKDEILMAGGVALNRRLRDMVTNMAREAGIRSYLTDREYCMDNGIMIAQAALLMYKSGVRMSV*
>P1;3WUH
structure:3WUH:7   :B:353 :B::Saccharomyces cerevisiae:2.937:
-KGYKVLAIETSCDDTCVSVLDRFSKSAAPNVLANLKDTL-----------KAHIHHQARIGPLTERALIESNA-REGIDLICVTRGPGMPGSLSGGLDFAKGLAVAWNKPLIGVHHMLGHLLIPRMGTNGKVPQFPFVSLLVSGGHTTFVLSRAIDDHEILCDTIDIAVGDSLDKCGRELGFKG-TMIAREMEKFINQDINDQDFALKLEMP-------SKRNMLSFSFSAFITALRTNLTKLGKTEIQELPEREIRSIAYQVQESVFDHIINKLKHVLKSQPEKFKNVREFVCSGGVSSNQRLRTKLETEL--------FNFYYPPMDLCSDNSIMIGWAGIEIWESL*
>P1;3ZEU
structure:3ZEU:2   :B:323 :B::SALMONELLA ENTERICA SUBSP. ENTERICA SEROVAR TYPHIMURIUM:1.653:
-------------------------RVLGIETSCDETGIAIYDDKKGLLANQLYSQVKLHADYGGVVPELASRDHVRKTVPLIQAALKEAGLTASDIDAVAYTAGPGLVGALLVGATVGRSLAFAWNVPAIPVHHMEGHLLAPMLEDNPPEFPFVALLVSGGHTQLISVTGIGQYELLGESIDDAAGEAFDKTAKLLGLDYPGGP--MLSKMASQGTAGRFVFPRPMTDRPGLDFSFSGLKTFAANTIRS-NGGDEQTRADIARAFEDAVVDTLMIKCKRALESTGFKRLVMAGGVSANRTLRAKLAEMMQKRRGEVFYARPEFCTDNGAMIAYAGMVRFKAGVTADLGV*
>P1;4K25
structure:4K25:9   :A:353 :A::Saccharomyces cerevisiae:2.88:
---YKVLAIETSCDDTCVSVLDRFSKSAAPNVLANLKDTLDS--------TKAHIHHQARIGPLTERALIESNA-REGIDLICVTRGPGMPGSLSGGLDFAKGLAVAWNKPLIGVHHMLGHLLIPRMGTNGKVPQFPFVSLLVSGGHTTFVLSRAIDDHEILCDTIDIAVGDSLDKCGRELGFKG-TMIAREMEKFINQDINDQDFALKLEM-----------NMLSFSFSAFITALRTNLTKLGKTEIQELPEREIRSIAYQVQESVFDHIINKLKHVLKSQPEKFKNVREFVCSGGVSSNQRLRTKLETELGTLNSTSFFNFYYPPMDLCSDNSIMIGWAGIEIWESL*
>P1;5JMV
structure:5JMV:4   :A:305 :A::Methanocaldococcus jannaschii (strain ATCC 43067 / DSM 2661 / JAL-1 / JCM 10045 / NBRC 100440):3.38646964319:
--------------------------------------DPMICLGLEGTAEKTGVGIVTSDGEVLFNKTIMY-KP-----NPREAADHHAETFPKLIKEAFEVV--DKNEIDLIAFSQGPGLGPSLRVTATVARTLSLTLKKPIIGVNHCIAHIEIGKLTTEAEDPLTLYVSGGNTQVIAYVSKKYRVFGETLDIAVGNCLDQFARYVNLPHP--GGPYIEELARKGKKLVDLPYTVKGMDIAFSGLLTAAMRA----YDA-GERLEDICYSLQEYAFSMLTEITERALAHTNKGEVMLVGGVAANNRLREMLKAMCEGQNVDFYVPPKEFCGDNGAMIAWLGLLMHKNG*
>P1;6GWJ
structure:6GWJ:2   :C:313 :C::Homo sapiens:1.95:
--------------------------------------PAVLGFEGSANKIGVGVVRDGKVLANPRRTYVTPPGTGFLPGDTARHHRAVILDLLQEALTESGLTSQDIDCIAYTKGPGMGAPLVSVAVVARTVAQLWNKPLVGVNHCIGHIEMGRLITGATSPTVLYVSGGNTQVIAYSEHRYRIFGETIDIAVGNCLDRFARVLKISNDPSPGYNIEQMAKRGKKLVELPYTVKGMDVSFSGILSFIEDVAHRMLATGECTPEDLCFSLQETVFAMLVEITERAMAHCGSQEALIVGGVGCNVRLQEMMATMCQERGARLFATDERFCIDNGAMIAQAGWEMFRAGHRT*
>P1;6N9A
structure:6N9A:2   :B:319 :B::Thermotoga maritima:6N9:
-----------------------GRMRVLGIETSCDETAVAVLDDGKNVVVNFTVSQIE-VHQKFGGVVPEVAARHHLKNLPILLKKAFE--KVPPETVDVVAATYGPGLIGALLVGLSAAKGLAISLEKPFVGVNHVEAHVQAVFLANPDLKPPLVVLMVSGGHTQLMKVDEDYSMEVLGETLDDSAGEAFDKVARLLGLGY--PGGPVIDRVAKKGDPEKYSFPRPMLDDDSYNFSFAGLKTSVL----YFLQREKGYKVEDVAASFQKAVVDILVEKTFRLARNLGIRKIAFVGGVAANSMLREEVRKRAERWNYEVFFPPLELCTDNALMVAKAGYEKAKRGMFSP*

