>P1;UKNP
sequence:UKNP:1    :A:329  :A::::
MGVKGLSTYLQQD-P----NNF--SSFE-------LHNTRVVIDAWNFINYLHRKY-----G------FTKLYGGEYMDFNLCIRDFLKRLRKCRISPIFLFDGCHSKEGTKLGNLLKKNRRRIE---PLNRLINQVRLLRPS-HV-E----H-Y-RPVPDICPSLTYETVMQILIEYKVPHLTCDGEADKSTAELAI--F-LD-C-PVLSNDSDFFLFRSVDSETNLQFILLDTLDATPMCREGLCDHC--KGQTYDKC-FSMIAQLYSATKC--SFSAFNPSLLPLIAVMIGNDVTS-PITNVSLTGNHCGPKDIRSVFKWLSNFGS*
>P1;1A77
structure:1A77:2   :A:246 :A::Methanocaldococcus jannaschii:2.0:
-GV-QFGDFIPKN-I----IS----FED-------LKGKKVAIDGMNALYQFLTSI-----RLRDGSPLRNRKGEITSAYNGVFYKTI-HLLENDITPIWVFDGEPPK--LKEKTRKVRREMKEKAELKMKEAIK------KE-DF-EEAAKY-A-KRVSY-LTPKMVENCKYLLSLMGIPYVEAPSEGEAQASYMAK-KG-DV-W-AVVSQDYDALLYGAPRV---VR--NLTTTK-------E---MP----ELIEL---NEVL----------EDLRISLDDLIDIAIFMGTDYNPGGVK-------GIGFKRA---YELVRSGV-*
>P1;1RXW
structure:1RXW:3   :C:257 :C::Archaeoglobus fulgidus:2.0:
--A-DIGDLFERE-E----VEL----EY-------FSGKKIAVDAFNTLYQFISII-----RQPDGTPLKDSQGRITSHLS-GILYRVSNMVEVGIRPVFVFDGEPPE--FKKAEIEERKKRRAE---AEEMWIAALQAG-DK-DA-K----K-Y-AQAAGRVDEYIVDSAKTLLSYMGIPFVDAPSEGEAQAAYMAAKGD-VE-Y--TGSQDYDSLLFGSPRLARN-----LAI---------------DVKPEIIIL---ESNL----------KRLGLTREQLIDIAILVGTDYNE-GV-------KGVGVKKA---LNYIKTYGD*
>P1;1UL1
structure:1UL1:1   :A:254 :A::Homo sapiens:2.9:
-GIQGLAKLIADV-APSAIREN--DIKS-------YFGRKVAIDASMSIYQFLIAV-------------------TTSHLMGMFYRTIRMM-ENGIKPVYVFDGKPP--QLKSGELAK---------------------------------------RLVKV-TKQHNDECKHLLSLMGIPYLDAPSEAEASCAALVK--A-GK-VYAAATEDMDCLTFGSPVL---MR--HLTASE-----KKL-------PIQEFHL---SRILQ----------ELGLNQEQFVDLCILLGSDYCE-SIRG-------IGPKRA---VDLIQKHKS*
>P1;1UL1
structure:1UL1:1   :C:254 :C::Homo sapiens:2.9:
-GIQGLAKLIADV-APSAIREN--DIKS-------YFGRKVAIDASMSIYQFLIAV-----R-QGGDVLQNEEGETTSHLMGMFYRTIRMM-ENGIKPVYVFDGKPPQ--LKSGELAKRSERRAE---AEKQLQQ------EQ-EV-E----KFT-KRLVKV-TKQHNDECKHLLSLMGIPYLDAPSEAEASCAALVK--A-GK-VYAAATEDMDCLTFGSPVL---M--RHLTASEA----KKL-------PIQEFHL---SRILQ----------ELGLNQEQFVDLCILLGSDYCE-SIRG-------IGPKRA---VDLIQKHKS*
>P1;3ORY
structure:3ORY:11  :A:273 :A::Desulfurococcus amylolyticus:2.0:
MGV-DLKDIIPGE-A----KTVIEDLRI-------LHGKIIVIDGYNALYQFLAAI-----RQPDGTPLMDNNGRITSHLSGLFYRTIN-IVEAGIKPVYVFDGKPP--ELKAREIERRKAVKEE---AAKKYEEAVQSGDLE-LA-R----R-Y-AMMSAKLTEEMVRDAKSLLDAMGIPWVQAPAEGEAQAAYIVK--K-GDAY-ASASQDYDSLLFGSPKL---VRN-----LTISGRRK----LPR--KNE-YV----EVKPELIELDKL-LVQLGITLENLIDIGILLGTDYNPDGFEG-------IGPK---KALQLVKAYGG*
>P1;3Q8L
structure:3Q8L:1   :A:248 :A::Homo sapiens:2.319:
-GIQGLAKLIADV-APSAIREN--DIKS-------YFGRKVAIDASMSIYQFLIAVRQGGDV------LQNEEGETTSHLMGMFYRTIRMM-ENGIKPVYVFDGKPP--QLKSGELAKRSERRAE---AEKQLQQAQAAGAEQ-EV-E----K-FTKRLVK-VTKQHNDECKHLLSLMGIPYLDAPSEAEASCAALVK--A-GKVY-AAATEDMDCLTFGSPV----LMR-HLTASE----AKKL-------PIQEFHL---SRILQEL----------GLNQEQFVDLCILLGSDYCE-SIRG-------IGPKRAVDL---------*
>P1;3QE9
structure:3QE9:2   :A:233 :A::Homo sapiens:2.51:
-GIQGLLQFIKEA-S----EPI--HVRK-------YKGQVVAVDTYCWLHKGAIAC-----A------EKLAKGEPTDRYVGFCMKFVNMLLSHGIKPILVFDGCTLP--SKKEVERSRRERRQA---NLLKGKQLLREGKVSEAR-E----C-F-TRSINITHA-MAHKVIKAARSQGVDCLVAPYEADAQLAYLNK--AGIV-Q-AIITEDSALLAFGCKKV------I--LKMDQF-----GNG-------LEIDQARLGMCRQL----G-----DVFTEEKFRYMCILSGCDYLS-SLRGI------------------------*
>P1;5CNQ
structure:5CNQ:1   :A:217 :A::Chaetomium thermophilum:2.602:
-GIKGIYKEIGSGER----ISL--CKLAIDHLEQHNRPLRLAIDMAIWQFQIQAA-----------------RGGSNPAIRTLFYRF-VRLLSLGIHPIFVFDGPNKP--------------------------------------------------------GVSTAMAKRLIRLFGFTAHDAPGEAEAECAYLEQ--Q-GI-VDAVLSEDVDTIMFGSRV-------TLRD-WSSE----GGPPTH----------------VTLHDAKKIAEGPSGLDREGMVLVALMSGG-----GIP-------GCGIKVACQAAK-------*
>P1;5CO8
structure:5CO8:1   :B:217 :B::Chaetomium thermophilum (strain DSM 1495 / CBS 144.50 / IMI 039719):2.4:
-GIKGIYKEIGSGER----ISL--CKLAIDHLEQHNRPLRLAIDMAIWQFQIQA-----------------ARGGSNPAIRTLFYRFV-RLLSLGIHPIFVFDGPNKP-------------------------------------------------------NGVSTAMAKRLIRLFGFTAHDAPGEAEAECAYLEQ--Q-GI-VDAVLSEDVDTIMFGSRVT-------LRD-WSSE-------GGP-------------PTHVTLHDAKKIAEGPSGLDREGMVLVALMSGGDYLPDGIP-------GCGIKVACQAAK-------*
>P1;5UM9
structure:5UM9:1   :A:239 :A::Homo sapiens:2.805:
-GIQGLAKLIADV-APSAIREN--DIKS-------YFGRKVAIDASMSIYQFLIAV-----R-QGGDVLQNEEGETTSHLMGMFYRTIRMM-ENGIKPVYVFNGKPP--QLKSGELAKRSERRAE---AEKQLQQAQAAGAEQ-EVEK----F-T-KRLVK-VTKQHNDECKHLLSLMGIPYLDAPSEAEASCAALVK--A-GK-VYAAATEDMDCLTFGSPV------LM--RHLTAS-EAKKL---PI----QEFHL---SRILQE----------LGLNQEQFVDLCILLGSDYCE-SIRG-------------------------*
>P1;5V07
structure:5V07:2   :A:233 :A::Homo sapiens:2.15:
-GIQGLLQFIKEA-S----EPI--HVRK-------YKGQVVAVDTYCWLHKGAIAC-----A------EKLAKGEPTDRYVGFCMKFVNMLLSHGIKPILVFDGCTLP--SKKEVERSRRERRQA---NLLKGKQLLREGKVSEAR-E----C-F-TRSINITHA-MAHKVIKAARSQGVDCLVAPYEADAQLAYLNK--AGIV-Q-AIITEDSALLAFGCKKV------I--LKMDQF-----GNG-------LEIDQARLGMCRQL----G-----DVFTEEKFRYMCILSGCDYLS-SLRGI------------------------*
>P1;5ZOD
structure:5ZOD:2   :A:240 :A::Homo sapiens:1.9:
-GIQGLAKLIADV-APSAIREN--DIKS-------YFGRKVAIDASMS------------------------------HLMGMFYRTIRMM-ENGIKPVYVFDGKPP--Q---------------------------------------------------------NDECKHLLSLMGIPYLDAPSEAEASCAALVK--A-GKVY-AAATEDMDCLTFGSPV---LMRH--LTASEA----KK-----L--PIQEFHL---SRILQ----------ELGLNQEQFVDLCILLGSDYCE-SIRG-------------------------*

